### ISSUE TITLE
AttributeError: 'MaildirDedupMail' object has no attribute '_subdir'

### ISSUE THREAD

**Issue by phoskin** [kdeldycke/mail-deduplicate#212] opened 2021-03-21 08:52 UTC
#### Preliminary checks

* [Y] I am running the latest version
* [Y] I have [read the Code of Conduct](https://github.com/kdeldycke/mail-deduplicate/blob/develop/.github/code-of-conduct.md)
* [Y] I have checked there is not other [Issues](https://github.com/kdeldycke/mail-deduplicate/issues) or [Pull Requests](https://github.com/kdeldycke/mail-deduplicate/pulls) covering the same topic to open

#### Describe the bug

mdedup crashes on stage 3. Processing quite an old large mailbox thats 22GB in size, in an AWS bigmem instance.

#### CLI output

buntu@ip-172-31-26-117:/mnt/data$ mdedup -i maildir -E Maildir.dedupe -e maildir --strategy discard-one Maildir.working

... shortened because the log output is 75MB lol ...

```shell-session
● Phase #3 - Perform action on selected mails
Perform copy-selected action...
228570 mails selected for action.
Creating new maildir box at /mnt/data/Maildir.dedupe2 ...
Traceback (most recent call last):
  File "/usr/local/bin/mdedup", line 8, in <module>
    sys.exit(mdedup())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mail_deduplicate/cli.py", line 388, in mdedup
    perform_action(dedup)
  File "/usr/local/lib/python3.8/dist-packages/mail_deduplicate/action.py", line 114, in perform_action
    method(dedup)
  File "/usr/local/lib/python3.8/dist-packages/mail_deduplicate/action.py", line 45, in copy_selected
    box.add(mail)
  File "/usr/lib/python3.8/mailbox.py", line 300, in add
    subdir = message.get_subdir()
  File "/usr/lib/python3.8/mailbox.py", line 1537, in get_subdir
    return self._subdir
AttributeError: 'MaildirDedupMail' object has no attribute '_subdir'
ubuntu@ip-172-31-26-117:/mnt/data$ 
```

#### Environment

```shell-session
ubuntu@ip-172-31-26-117:/mnt/data$ mdedup --version
mdedup 6.1.2
{'username': '-', 'guid': 'aca492c9d1980c11b4cf243dfce1f1c', 'hostname': '-', 'hostfqdn': '-', 'uname': {'system': 'Linux', 'node': '-', 'release': '5.4.0-1038-aws', 'version': '#40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021', 'machine': 'x86_64', 'processor': 'x86_64'}, 'linux_dist_name': '', 'linux_dist_version': '', 'cpu_count': 8, 'fs_encoding': 'utf-8', 'ulimit_soft': 1024, 'ulimit_hard': 1048576, 'cwd': '-', 'umask': '0o2', 'python': {'argv': '-', 'bin': '-', 'version': '3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]', 'compiler': 'GCC 9.3.0', 'build_date': 'Jan 27 2021 15:41:15', 'version_info': [3, 8, 5, 'final', 0], 'features': {'openssl': 'OpenSSL 1.1.1f  31 Mar 2020', 'expat': 'expat_2.2.9', 'sqlite': '3.31.1', 'tkinter': '', 'zlib': '1.2.11', 'unicode_wide': True, 'readline': True, '64bit': True, 'ipv6': True, 'threading': True, 'urandom': True}}, 'time_utc': '2021-03-21 08:39:40.079125', 'time_utc_offset': 0.0, '_eco_version': '1.0.1'}
```

#### Additional context

Any help would be great! Thanks!

**Comment by kdeldycke** [comment] 2021-03-21 12:57
This is a duplicate of #191.

**Closed by kdeldycke** 2021-03-21 12:57 UTC
Labels: bug
