### ISSUE TITLE
Error in move or copy action on Maildir

### ISSUE THREAD

**Issue by nutria007** [kdeldycke/mail-deduplicate#135] opened 2020-12-14 18:19 UTC
Error ocurs when deduping a Maildir mailbox , using move-selected or copy-selected

   Command:
```
mdedup -d -i maildir -s select-one -a copy-selected -e maildir -E /path/to/desination /path/to/source
```

The Python traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/mdedup", line 11, in <module>
    sys.exit(mdedup())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mail_deduplicate/cli.py", line 388, in mdedup
    perform_action(dedup)
  File "/usr/local/lib/python3.7/dist-packages/mail_deduplicate/action.py", line 114, in perform_action
    method(dedup)
  File "/usr/local/lib/python3.7/dist-packages/mail_deduplicate/action.py", line 45, in copy_selected
    box.add(mail)
  File "/usr/lib/python3.7/mailbox.py", line 300, in add
    subdir = message.get_subdir()
  File "/usr/lib/python3.7/mailbox.py", line 1538, in get_subdir
    return self._subdir
AttributeError: 'MaildirDedupMail' object has no attribute '_subdir'
```
#### Environment

`$ mdedup --version`:
```
mdedup 6.0.2
{'username': '-', 'guid': 'c724421a0ad9872be2e25190548e22', 'hostname': '-', 'hostfqdn': '-', 'uname': {'system': 'Linux', 'node': '-', 'release': '4.15.0-124-generic', 'version': '#127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020', 'machine': 'x86_64', 'processor': 'x86_64'}, 'linux_dist_name': 'Ubuntu', 'linux_dist_version': '18.04', 'cpu_count': 4, 'fs_encoding': 'utf-8', 'ulimit_soft': 1024, 'ulimit_hard': 1048576, 'cwd': '-', 'umask': '0o2', 'python': {'argv': '-', 'bin': '-', 'version': '3.7.5 (default, Nov 7 2019, 10:50:52) [GCC 8.3.0]', 'compiler': 'GCC 8.3.0', 'build_date': 'Nov  7 2019 10:50:52', 'version_info': [3, 7, 5, 'final', 0], 'features': {'openssl': 'OpenSSL 1.1.1  11 Sep 2018', 'expat': 'expat_2.2.5', 'sqlite': '3.22.0', 'tkinter': '', 'zlib': '1.2.11', 'unicode_wide': True, 'readline': True, '64bit': True, 'ipv6': True, 'threading': True, 'urandom': True}}, 'time_utc': '2020-12-14 18:10:26.960528', 'time_utc_offset': -3.0, '_eco_version': '1.0.1'}
```

**Comment by kdeldycke** [comment] 2021-03-21 12:58
This is a duplicate of #191.

**Closed by kdeldycke** 2021-03-21 12:58 UTC
Labels: bug
